name: my_workspace

packages:
  - lib/**
  - packages/**

scripts:
  build:all:
    run: melos exec -c 1 -- "flutter pub get && flutter pub run build_runner build"

  build:di:
    run: melos exec -c 1 -- "flutter pub run build_runner build"

  build:design:
    run: melos exec -c 1 --scope=design -- "flutter pub get && flutter pub run build_runner build"

  build:presentation:
    run: melos exec -c 1 --scope=presentation -- "flutter pub run build_runner build"

  build:data:
    run: melos exec -c 1 --scope=data -- "flutter pub run build_runner build"

  build:domain:
    run: melos exec -c 1 --scope=domain -- "flutter pub run build_runner build"

  clean:
    run: melos exec -- flutter clean

  analyze:
    run: melos exec -- flutter analyze
